# Setup
title:               Maxwell Svetlik
tagline:             ''
description:         ''
url:                 http://maxwellsvetlik.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Maxwell Svetlik
  url:               http://maxwellsvetlik.com
  email:             max@maxwellsvetlik.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
#google_analytics_id: #UA-XXXX-Y
