# Setup
title:               Maxwell Svetlik
tagline:             ''
description:         ''
url:                 https://maxsvetlik.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Maxwell Svetlik
  url:               https://maxsvetlik.github.io
  email:             max@maxwellsvetlik.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
